use octocrab::Octocrab;
use anyhow::Result;

pub struct GitHubReporter {
    octo: Octocrab,
    repo_owner: String,
    repo_name: String,
}

impl GitHubReporter {
    pub fn new(token: String) -> Result<Self> {
        // Der Token wird jetzt von außen (aus der .env) übergeben
        let octo = Octocrab::builder()
            .personal_token(token)
            .build()?;
            
        Ok(Self {
            octo,
            repo_owner: "adnan19825".to_string(),
            repo_name: "Easy-Eva-Studio-v7.5".to_string(),
        })
    }
    
    pub async fn create_security_alert(
        &self,
        verdict: &str,
        score: u8,
        details: &str
    ) -> Result<String> {
        let title = format!("🚨 [NODE-ALERT] {}", verdict);
        let body = format!(
            "### 🛡️ Security Report\n\n**Status:** `{}`\n**Score:** `{}`\n\n**Details:**\n```\n{}\n```\n\n---\n*Generated by Easy-Eva Sonic v10.2*",
            verdict, score, details
        );

        let issue = self.octo
            .issues(&self.repo_owner, &self.repo_name)
            .create(title)
            .body(body)
            .labels(vec!["automated-alert".to_string()])
            .send()
            .await?;
            
        Ok(issue.html_url.to_string())
    }
}

